import type { Category, Company, Product, ProductType } from "./types";

export const categories: Category[] = [
  {
    id: "kfz",
    name: "Автомобили и запчасти",
    description:
      "Легковые и коммерческие машины, запчасти из ФРГ и партнёрских заводов (АИ 1992).",
  },
  {
    id: "musik",
    name: "Музыкальная торговля",
    description:
      "Инструменты, студия, звукоусиление — от Томанна до узкоспециализированных мастерских.",
  },
  {
    id: "hifi",
    name: "Электроника и Hi-Fi",
    description: "Домашнее аудио, портативная техника, профессиональное звуковое оборудование.",
  },
  {
    id: "werkstatt",
    name: "Мастерская и принадлежности",
    description: "Инструмент, расходники, средства защиты.",
  },
];

export const companies: Company[] = [
  { id: "bmw", categoryId: "kfz", name: "БМВ АГ", hq: "Мюнхен", founded: 1916 },
  {
    id: "mb",
    categoryId: "kfz",
    name: "Мерседес-Бенц",
    hq: "Штутгарт",
    founded: 1926,
  },
  { id: "vw", categoryId: "kfz", name: "Фольксваген АГ", hq: "Вольфсбург", founded: 1937 },
  { id: "audi", categoryId: "kfz", name: "Ауди NSU Авто Юнион АГ", hq: "Ингольштадт", founded: 1909 },
  { id: "porsche", categoryId: "kfz", name: "Доктор Инг. Порше АГ", hq: "Штутгарт-Цуффенхаузен", founded: 1931 },
  { id: "opel", categoryId: "kfz", name: "Адам Опель АГ", hq: "Рюссельсхайм", founded: 1862 },
  { id: "bosch", categoryId: "kfz", name: "Роберт Бош ГмбХ", hq: "Штутгарт", founded: 1886 },
  { id: "continental", categoryId: "kfz", name: "Континенталь АГ", hq: "Ганновер", founded: 1871 },
  { id: "zf", categoryId: "kfz", name: "ЦФ Фридрихсхафен АГ", hq: "Фридрихсхафен", founded: 1915 },
  { id: "hella", categoryId: "kfz", name: "Хелла КГ", hq: "Липпштадт", founded: 1899 },
  { id: "mahle", categoryId: "kfz", name: "Мале ГмбХ", hq: "Штутгарт", founded: 1920 },
  { id: "thomann", categoryId: "musik", name: "Томанн ГмбХ", hq: "Бургебрах", founded: 1954 },
  { id: "harleybenton", categoryId: "musik", name: "Харли Бентон (Томанн)", hq: "Бургебрах", founded: 1990 },
  { id: "framus", categoryId: "musik", name: "Фрамус / Ворвик", hq: "Маркнойкирхен", founded: 1946 },
  { id: "hofner", categoryId: "musik", name: "Карл Хёфнер ГмбХ", hq: "Бубенройт", founded: 1887 },
  { id: "schimmel", categoryId: "musik", name: "Вильгельм Шиммель (рояли и пианино)", hq: "Брауншвейг", founded: 1885 },
  { id: "steinberg", categoryId: "musik", name: "Штайнберг Медиа", hq: "Гамбург", founded: 1984 },
  { id: "sennheiser", categoryId: "hifi", name: "Зеннхайзер электроник", hq: "Ведемарк", founded: 1945 },
  { id: "beyerdynamic", categoryId: "hifi", name: "Бейердайнамик", hq: "Хайльбронн", founded: 1924 },
  { id: "neumann", categoryId: "hifi", name: "Георг Нойманн ГмбХ", hq: "Берлин", founded: 1928 },
  { id: "braun", categoryId: "hifi", name: "Браун АГ", hq: "Кронберг", founded: 1921 },
  { id: "telefunken", categoryId: "hifi", name: "Телефункен электроник", hq: "Берлин", founded: 1903 },
  { id: "hazet", categoryId: "werkstatt", name: "Хазет-Верк", hq: "Ремшайд", founded: 1868 },
  { id: "wera", categoryId: "werkstatt", name: "Вера (инструмент)", hq: "Вупперталь", founded: 1936 },
  { id: "uvex", categoryId: "werkstatt", name: "Ювекс (средства защиты)", hq: "Фюрт", founded: 1926 },
];

export const productTypes: ProductType[] = [
  { id: "pkw", categoryId: "kfz", name: "Легковой / седан" },
  { id: "sport", categoryId: "kfz", name: "Купе / спорт" },
  { id: "suv", categoryId: "kfz", name: "Внедорожник / универсал" },
  { id: "nutzfahrzeug", categoryId: "kfz", name: "Коммерческий транспорт" },
  { id: "motor", categoryId: "kfz", name: "Двигатель и трансмиссия" },
  { id: "fahrwerk", categoryId: "kfz", name: "Подвеска и шины" },
  { id: "elektrik", categoryId: "kfz", name: "Электрика и свет" },
  { id: "gitarre", categoryId: "musik", name: "Гитары и бас-гитары" },
  { id: "tasten", categoryId: "musik", name: "Клавишные" },
  { id: "schlagzeug", categoryId: "musik", name: "Ударные и перкуссия" },
  { id: "studio", categoryId: "musik", name: "Студия и запись" },
  { id: "beschallung", categoryId: "musik", name: "Звукоусиление и PA" },
  { id: "kopfhoerer", categoryId: "hifi", name: "Наушники" },
  { id: "mikrofon", categoryId: "hifi", name: "Микрофоны" },
  { id: "anlage", categoryId: "hifi", name: "Стереосистемы" },
  { id: "tragbar", categoryId: "hifi", name: "Портативная техника" },
  { id: "werkzeug", categoryId: "werkstatt", name: "Ручной инструмент" },
  { id: "schutz", categoryId: "werkstatt", name: "Средства защиты" },
];

export const products: Product[] = [
  {
    id: "bmw-e34-520i",
    categoryId: "kfz",
    companyId: "bmw",
    typeId: "pkw",
    name: "BMW 520i (E34), седан",
    sku: "BMW-E34-520I-92",
    priceDm: 42900,
    yearModel: 1992,
    details: "Рядная шестёрка 2,0 л, 24 клапана, кожа по заказу, катализатор опционально.",
  },
  {
    id: "bmw-e36-318is",
    categoryId: "kfz",
    companyId: "bmw",
    typeId: "sport",
    name: "BMW 318is (E36), купе",
    sku: "BMW-E36-318IS",
    priceDm: 38900,
    yearModel: 1992,
    details: "Спортивная подвеска, пакет внешнего вида M-Technik по запросу.",
  },
  {
    id: "mb-w124-300e",
    categoryId: "kfz",
    companyId: "mb",
    typeId: "pkw",
    name: "Mercedes-Benz 300 E (W124)",
    sku: "MB-W124-300E",
    priceDm: 51200,
    yearModel: 1992,
    details: "Седан для дальних поездок, АКПП 4 ступени.",
  },
  {
    id: "mb-r129-500sl",
    categoryId: "kfz",
    companyId: "mb",
    typeId: "sport",
    name: "Mercedes-Benz 500 SL (R129)",
    sku: "MB-R129-500SL",
    priceDm: 128000,
    yearModel: 1992,
    details: "Родстер V8, электропривод складного верха.",
  },
  {
    id: "vw-golf3-gti",
    categoryId: "kfz",
    companyId: "vw",
    typeId: "sport",
    name: "VW Golf III GTI 16V",
    sku: "VW-G3-GTI16",
    priceDm: 28900,
    yearModel: 1992,
    details: "Компактный «городской» спорткар, сиденья Recaro опционально.",
  },
  {
    id: "vw-passat-b4",
    categoryId: "kfz",
    companyId: "vw",
    typeId: "pkw",
    name: "VW Passat B4 Variant 2.0",
    sku: "VW-B4-VAR-20",
    priceDm: 31900,
    yearModel: 1992,
    details: "Большой универсал, удобен для торговли и РП-логистики.",
  },
  {
    id: "audi-80-b4",
    categoryId: "kfz",
    companyId: "audi",
    typeId: "pkw",
    name: "Audi 80 B4 2.0 E",
    sku: "AUD-B4-80-20",
    priceDm: 33500,
    yearModel: 1992,
    details: "Опция Quattro для зимних условий.",
  },
  {
    id: "audi-c4-100",
    categoryId: "kfz",
    companyId: "audi",
    typeId: "pkw",
    name: "Audi 100 (C4) 2.8 E",
    sku: "AUD-C4-100-28",
    priceDm: 49800,
    yearModel: 1992,
    details: "Представительский седан, двигатель V6.",
  },
  {
    id: "porsche-964-c2",
    categoryId: "kfz",
    companyId: "porsche",
    typeId: "sport",
    name: "Porsche 911 Carrera 2 (964)",
    sku: "POR-964-C2",
    priceDm: 98500,
    yearModel: 1992,
    details: "Оппозит 3,6 л, без Tiptronic — чистое удовольствие от вождения.",
  },
  {
    id: "porsche-928-gts",
    categoryId: "kfz",
    companyId: "porsche",
    typeId: "sport",
    name: "Porsche 928 GTS",
    sku: "POR-928-GTS",
    priceDm: 142000,
    yearModel: 1992,
    details: "GT-класс люкс, V8 спереди — альтернатива линейке 911.",
  },
  {
    id: "opel-omega-a",
    categoryId: "kfz",
    companyId: "opel",
    typeId: "pkw",
    name: "Opel Omega A 3.0 24V",
    sku: "OPE-OM-A-30",
    priceDm: 36800,
    yearModel: 1992,
    details: "Классика служебного автомобиля, просторный салон.",
  },
  {
    id: "opel-frontera",
    categoryId: "kfz",
    companyId: "opel",
    typeId: "suv",
    name: "Opel Frontera A Sport",
    sku: "OPE-FRO-A-S",
    priceDm: 41200,
    yearModel: 1992,
    details: "Проходимость для бездорожья, удобна для РП у границ.",
  },
  {
    id: "bosch-batterie",
    categoryId: "kfz",
    companyId: "bosch",
    typeId: "elektrik",
    name: "Стартерная АКБ Bosch Silver Star 12 В 74 А·ч",
    sku: "BOS-S74",
    priceDm: 289,
    details: "Морозостойкая, для среднего класса легковых.",
  },
  {
    id: "continental-conticontact",
    categoryId: "kfz",
    companyId: "continental",
    typeId: "fahrwerk",
    name: "Шина Continental ContiContact CH95 195/65 R15",
    sku: "CON-CH95-19565",
    priceDm: 118,
    details: "Цена за одну штуку, склад сезонный.",
  },
  {
    id: "zf-getriebeoel",
    categoryId: "kfz",
    companyId: "zf",
    typeId: "motor",
    name: "Трансмиссионная жидкость ZF Lifeguard ATF (1 л)",
    sku: "ZF-LG-ATF-1L",
    priceDm: 24,
    details: "Для АКПП ZF 1990-х годов.",
  },
  {
    id: "hella-h4-set",
    categoryId: "kfz",
    companyId: "hella",
    typeId: "elektrik",
    name: "Галогеновые лампы Hella H4, двойная упаковка",
    sku: "HEL-H4-2",
    priceDm: 19,
    details: "Сертификация E, безопасные ночные поездки в РП.",
  },
  {
    id: "mahle-kolbenring",
    categoryId: "kfz",
    companyId: "mahle",
    typeId: "motor",
    name: "Комплект поршневых колец Mahle R4, стандарт",
    sku: "MAH-KRS-R4",
    priceDm: 210,
    details: "Для мастерской, под заказ возможна доработка.",
  },
  {
    id: "thomann-hb-tele",
    categoryId: "musik",
    companyId: "harleybenton",
    typeId: "gitarre",
    name: "Harley Benton TE-52 NA Vintage Series",
    sku: "HB-TE52-NA",
    priceDm: 189,
    details: "Электрогитара в стиле Tele, клён / корпус липа.",
  },
  {
    id: "thomann-hb-jb75",
    categoryId: "musik",
    companyId: "harleybenton",
    typeId: "gitarre",
    name: "Harley Benton JB-75MN Vintage Series, бас",
    sku: "HB-JB75-MN",
    priceDm: 219,
    details: "Отсылка к J-Bass, гриф клён.",
  },
  {
    id: "thomann-hb-sc500",
    categoryId: "musik",
    companyId: "harleybenton",
    typeId: "gitarre",
    name: "Harley Benton SC-500 BK Classic Series",
    sku: "HB-SC500-BK",
    priceDm: 199,
    details: "Singlecut, хамбакеры — рок и блюз.",
  },
  {
    id: "thomann-hb-d120ce",
    categoryId: "musik",
    companyId: "harleybenton",
    typeId: "gitarre",
    name: "Harley Benton D-120CE NT, акустика",
    sku: "HB-D120CE-NT",
    priceDm: 149,
    details: "Вырез грифа, система Fishman ISY-301 опционально.",
  },
  {
    id: "thomann-case-electric",
    categoryId: "musik",
    companyId: "thomann",
    typeId: "gitarre",
    name: "Кейс Thomann для электрогитары, ABS",
    sku: "TH-CASE-EG-ABS",
    priceDm: 89,
    details: "Для гастролей, поролоновая обивка.",
  },
  {
    id: "thomann-mixer-6",
    categoryId: "musik",
    companyId: "thomann",
    typeId: "studio",
    name: "Мини-микшер Thomann, 6 каналов (каталожная модель)",
    sku: "TH-MIX-6CH",
    priceDm: 129,
    details: "Компактный вариант для репточки и малых выступлений.",
  },
  {
    id: "thomann-cable-set",
    categoryId: "musik",
    companyId: "thomann",
    typeId: "studio",
    name: "Набор кабелей Thomann Jack-Jack 6 м, 3 шт.",
    sku: "TH-JJ-6M-3",
    priceDm: 39,
    details: "Разъёмы уровня Neutrik, подходит для студии.",
  },
  {
    id: "thomann-monitor-8",
    categoryId: "musik",
    companyId: "thomann",
    typeId: "beschallung",
    name: "Пассивные мониторы Thomann 8\" PA (пара)",
    sku: "TH-PA-MON-8P",
    priceDm: 329,
    details: "Для небольших клубов и РП в общественных залах.",
  },
  {
    id: "framus-panthera",
    categoryId: "musik",
    companyId: "framus",
    typeId: "gitarre",
    name: "Framus Panthera Studio Supreme",
    sku: "FR-PANT-SUP",
    priceDm: 1890,
    details: "Немецкое производство, сбалансированная конфигурация HSS.",
  },
  {
    id: "hofner-bass-500",
    categoryId: "musik",
    companyId: "hofner",
    typeId: "gitarre",
    name: "Höfner 500/1 Violin Bass",
    sku: "HF-5001-VB",
    priceDm: 2490,
    details: "Эстетика «битлов», короткая мензура.",
  },
  {
    id: "schimmel-k116",
    categoryId: "musik",
    companyId: "schimmel",
    typeId: "tasten",
    name: "Акустическое пианино Schimmel K 116 Tradition",
    sku: "SCH-K116-TR",
    priceDm: 12900,
    details: "Для салона и занятий.",
  },
  {
    id: "steinberg-cubase-at",
    categoryId: "musik",
    companyId: "steinberg",
    typeId: "studio",
    name: "Steinberg Cubase Audio для Atari (модуль + руководство)",
    sku: "ST-CB-AT-92",
    priceDm: 890,
    details: "Цифровая обработка звука — флагман начала 90-х.",
  },
  {
    id: "thomann-drumpad",
    categoryId: "musik",
    companyId: "thomann",
    typeId: "schlagzeug",
    name: "Электронные пэды Thomann, 8 зон",
    sku: "TH-EDP-8Z",
    priceDm: 279,
    details: "Выход MIDI, для домашней студии.",
  },
  {
    id: "sennheiser-hd540",
    categoryId: "hifi",
    companyId: "sennheiser",
    typeId: "kopfhoerer",
    name: "Sennheiser HD 540 Reference",
    sku: "SEN-HD540",
    priceDm: 349,
    details: "Открытые референс-наушники, детальное звучание.",
  },
  {
    id: "sennheiser-md421",
    categoryId: "hifi",
    companyId: "sennheiser",
    typeId: "mikrofon",
    name: "Sennheiser MD 421-II",
    sku: "SEN-MD421",
    priceDm: 420,
    details: "Динамический микрофон для малых барабанов, томов, речи.",
  },
  {
    id: "beyerdynamic-dt770",
    categoryId: "hifi",
    companyId: "beyerdynamic",
    typeId: "kopfhoerer",
    name: "beyerdynamic DT 770 Pro 250 Ом",
    sku: "BYD-DT770-250",
    priceDm: 289,
    details: "Студийный стандарт, закрытый тип.",
  },
  {
    id: "beyerdynamic-m88",
    categoryId: "hifi",
    companyId: "beyerdynamic",
    typeId: "mikrofon",
    name: "beyerdynamic M 88 TG",
    sku: "BYD-M88TG",
    priceDm: 510,
    details: "Универсальный динамический микрофон.",
  },
  {
    id: "neumann-u87",
    categoryId: "hifi",
    companyId: "neumann",
    typeId: "mikrofon",
    name: "Neumann U 87 Ai (стиль ранней серии)",
    sku: "NEU-U87-AI",
    priceDm: 4200,
    details: "Большая мембрана — эталон для вокала и РП-радио.",
  },
  {
    id: "braun-atelier",
    categoryId: "hifi",
    companyId: "braun",
    typeId: "anlage",
    name: "Линейка Braun Atelier Hi-Fi (ресивер RC)",
    sku: "BR-ATL-RC",
    priceDm: 1890,
    details: "Дизайн-классика, модульное расширение.",
  },
  {
    id: "telefunken-rc2000",
    categoryId: "hifi",
    companyId: "telefunken",
    typeId: "tragbar",
    name: "Портативный CD-плеер Telefunken RC 2000",
    sku: "TF-RC2000",
    priceDm: 799,
    details: "Anti-Shock, для командировок и сцен.",
  },
  {
    id: "hazet-knarren",
    categoryId: "werkstatt",
    companyId: "hazet",
    typeId: "werkzeug",
    name: "Трещотка Hazet реверсивная 1/2\", мод. 88",
    sku: "HAZ-88",
    priceDm: 95,
    details: "Производство Ремшайд.",
  },
  {
    id: "wera-kraftform",
    categoryId: "werkstatt",
    companyId: "wera",
    typeId: "werkzeug",
    name: "Набор отвёрток Wera Kraftform",
    sku: "WER-KF-SET",
    priceDm: 64,
    details: "Эргономичная рукоятка, лазерная насечка на жалах.",
  },
  {
    id: "uvex-brille",
    categoryId: "werkstatt",
    companyId: "uvex",
    typeId: "schutz",
    name: "Защитные очки uvex super f OTG",
    sku: "UVX-SF-OTG",
    priceDm: 18,
    details: "Для мастерской и лаборатории в РП.",
  },
];
